workflows:
  android-workflow:
    name: Android Workflow
    max_build_duration: 60
    environment:
      android_signing:
        - upload
      vars:
        PACKAGE_NAME: "io.codemagic.andrew_morley_app"
      groups:
        - firebase_credentials
      flutter: 3.38.3
    scripts:
      - name: Set up local.properties
        script: | 
          echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/android/local.properties"
      - name: Get Flutter packages
        script: | 
          flutter pub get
      - name: Build APK with Flutter
        script: | 
          # BUILD_NUMBER=$(($(google-play get-latest-build-number --package-name "$PACKAGE_NAME" --tracks="$GOOGLE_PLAY_TRACK") + 1))      
          flutter build appbundle --release \
            --build-name=1.0.$BUILD_NUMBER \
            --build-number=$BUILD_NUMBER
    artifacts:
      - build/**/outputs/**/*.apk
      - build/**/outputs/**/mapping.txt
      - flutter_drive.log
    publishing:
      email:
        recipients:
          - portchesterroad@gmail.com
        notify:
          success: true
          failure: false
      firebase:
        firebase_service_account: $FIREBASE_SERVICE_ACCOUNT
        android:
          app_id: 1:163547311856:android:5d83dec0fd2beb089a1c35      
          groups: 
            - androidTesters
