workflows:
  android-workflow:
    name: Android Workflow
    max_build_duration: 60
    environment:
      android_signing:
        - upload
      vars:
        PACKAGE_NAME: "io.codemagic.AndrewMorleyApp"
      groups:
        - firebase_credentials
      flutter: 3.38.3
    scripts:
      - name: Set up local.properties
        script: | 
          echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/android/local.properties"
      - name: Get Flutter packages
        script: | 
          flutter pub get
      - name: Build APK with Flutter
        script: | 
          flutter build apk --release \
            --build-name=1.0.$BUILD_NUMBER \
            --build-number=$BUILD_NUMBER
    artifacts:
      - build/app/outputs/apk/release/*.apk
      - build/**/outputs/**/mapping.txt
      - flutter_drive.log
    publishing:
      firebase:
        firebase_service_account: $FIREBASE_SERVICE_ACCOUNT
        android:
          app_id: 1:163547311856:android:5d83dec0fd2beb089a1c35      
          groups: 
            - androidTesters
